### PR TITLE
Here are the screenshots of our site interface based on wix development

### PR DESCRIPTION
**Pull request by Chiashen72**

### CODE REVIEW

**Comment by Wang-572** [comment]
Thanks! Don't forget to add descriptions about the page functionalities

**Comment by hh1889** [comment]
Looks like there is missing part - login page. I will help you upload

**Comment by Chiashen72** [comment]
Oh I forgot. Thank you

**Comment by NorDayana** [comment]
I think all is good for the wix interface

**Comment by Wang-572** [comment]
Alright, then i'll merge and close this pull

**Pull request merged**
