### PR TITLE
Upload User Manual - Cart & Payment

### PR DESCRIPTION
**Pull request by Chiashen72**

### CODE REVIEW

**Comment by Chiashen72** [comment]
I have made changes

**Comment by NorDayana** [comment]
Thank you. Now mobile part screenshot done

**Comment by hh1889** [comment]
Good

**Comment by hh1889** [comment]
Don't forget to add the description later

**Comment by Wang-572** [comment]
okay, will do

**Comment by hh1889** [comment]
Thanks

**Pull request merged**
